CREATE TABLE IF NOT EXISTS "ankits_portfolio_replies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ankits_portfolio_replies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"comment_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ankits_portfolio_replies" ADD CONSTRAINT "ankits_portfolio_replies_comment_id_ankits_portfolio_comments_id_fk" FOREIGN KEY ("comment_id") REFERENCES "public"."ankits_portfolio_comments"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ankits_portfolio_replies" ADD CONSTRAINT "ankits_portfolio_replies_user_id_ankits_portfolio_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."ankits_portfolio_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
